### ISSUE TITLE
Unable to compile on AArch64 Linux

### ISSUE THREAD

**Issue by tom91136** [d-dimitrova/KSgeneral#1]
When installing the package, I eventually hit the following error:
```
* installing to library ‘/root/tmp/libdir’
* installing *source* package ‘KSgeneral’ ...
** package ‘KSgeneral’ successfully unpacked and MD5 sums checked
** using staged installation
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for FFTW... yes
configure: creating ./config.status
config.status: creating src/Makevars
** libs
using C++ compiler: ‘g++ (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3)’
g++ -std=gnu++17 -I"/root/r/dist/include" -DNDEBUG -I/usr/local/include   -I'/root/tmp/libdir/Rcpp/include' -I/usr/local/include '-D_FORTIFY_SOURCE=2'   -fPIC  -g -O2 -Wall -pedantic -Wno-ignored-attributes -Wno-parentheses -fexceptions -fstack-protector-strong -fstack-clash-protection    -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++17 -I"/root/r/dist/include" -DNDEBUG -I/usr/local/include   -I'/root/tmp/libdir/Rcpp/include' -I/usr/local/include '-D_FORTIFY_SOURCE=2'   -fPIC  -g -O2 -Wall -pedantic -Wno-ignored-attributes -Wno-parentheses -fexceptions -fstack-protector-strong -fstack-clash-protection    -c cont_ks_dist.cpp -o cont_ks_dist.o
g++ -std=gnu++17 -I"/root/r/dist/include" -DNDEBUG -I/usr/local/include   -I'/root/tmp/libdir/Rcpp/include' -I/usr/local/include '-D_FORTIFY_SOURCE=2'   -fPIC  -g -O2 -Wall -pedantic -Wno-ignored-attributes -Wno-parentheses -fexceptions -fstack-protector-strong -fstack-clash-protection    -c crossprob_new.cc -o crossprob_new.o
g++ -std=gnu++17 -I"/root/r/dist/include" -DNDEBUG -I/usr/local/include   -I'/root/tmp/libdir/Rcpp/include' -I/usr/local/include '-D_FORTIFY_SOURCE=2'   -fPIC  -g -O2 -Wall -pedantic -Wno-ignored-attributes -Wno-parentheses -fexceptions -fstack-protector-strong -fstack-clash-protection    -c fftw_wrappers.cc -o fftw_wrappers.o
g++ -std=gnu++17 -I"/root/r/dist/include" -DNDEBUG -I/usr/local/include   -I'/root/tmp/libdir/Rcpp/include' -I/usr/local/include '-D_FORTIFY_SOURCE=2'   -fPIC  -g -O2 -Wall -pedantic -Wno-ignored-attributes -Wno-parentheses -fexceptions -fstack-protector-strong -fstack-clash-protection    -c fftwconvolver.cc -o fftwconvolver.o
g++ -std=gnu++17 -I"/root/r/dist/include" -DNDEBUG -I/usr/local/include   -I'/root/tmp/libdir/Rcpp/include' -I/usr/local/include '-D_FORTIFY_SOURCE=2'   -fPIC  -g -O2 -Wall -pedantic -Wno-ignored-attributes -Wno-parentheses -fexceptions -fstack-protector-strong -fstack-clash-protection    -c k2sample_stable1.cpp -o k2sample_stable1.o
In file included from fftw_wrappers.cc:5:
aligned_mem.h:6:10: fatal error: mm_malloc.h: No such file or directory
    6 | #include "mm_malloc.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [/root/r/dist/etc/Makeconf:202: fftw_wrappers.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from fftwconvolver.cc:6:
aligned_mem.h:6:10: fatal error: mm_malloc.h: No such file or directory
    6 | #include "mm_malloc.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [/root/r/dist/etc/Makeconf:202: fftwconvolver.o] Error 1
ERROR: compilation failed for package ‘KSgeneral’
* removing ‘/root/tmp/libdir/KSgeneral’
```

Looking at the error, I can see `mm_malloc.h` in included for `_mm_malloc` in https://github.com/d-dimitrova/KSgeneral/blob/master/src/aligned_mem.h.
This is a portability issue as `mm_malloc.h` is not part of any standard; some compilers provide this on x86_64 only.
For example this issue does not manifest on ARM M1 Macs because the compiler is Clang which provides this header where as GCC does not on Linux AArch64.

I think we can replace that header with normal POSIX headers on Linux while keeping Windows happy:
```cpp

#ifdef _MSC_VER 
    #include "mm_malloc.h" 
#else
    #include <cstdlib>
#endif

// later at malloc site
#ifdef _MSC_VER 
    _mm_malloc(size, ALIGNMENT)
#else 
    std::aligned_alloc(ALIGNMENT, size)
#endif

// and free site
#ifdef _MSC_VER 
    _mm_free(ptr)
#else 
    std::free(p)
#endif
```

I'm happy to open a PR to fix this.

**Comment by fakecloudsjy** [comment]
We do appreciate your kindness and supporting comment. For the use of KSgeneral package on a machine without x86_64 compilers, one could refer to this amendment and build accordingly.
However, we may not include this change into this repository for now. As this is the github repository corresponding to the CRAN submission of package KSgeneral https://cran.r-project.org/package=KSgeneral
Our intension for the CRAN repository is to maintain stability while allowing the package can be directly used on a considerable acceptable range (see in https://cran.r-project.org/web/checks/check_results_KSgeneral.html )
By default, all the CRAN repositories should be available with x86_64 compilers (see more in the R FAQ and the above link). Other ways of building CRAN package is usually beyond the standard of CRAN.

**Comment by pat-s** [comment]
I also encountered this issue.

> By default, all the CRAN repositories should be available with x86_64 compilers (see more in the R FAQ and the above link). **Other ways of building CRAN package is usually beyond the standard of CRAN.**

This statement is wrong.
CRAN does not enforce/advertise in any way to only build on `x86_64`. In fact, arm64 binaries exist for macOS and compilation should also succeed on arm64 on Linux.

> Our intension for the CRAN repository is to maintain stability while allowing the package can be directly used on a considerable acceptable range (see in [cran.r-project.org/web/checks/check_results_KSgeneral.html](https://cran.r-project.org/web/checks/check_results_KSgeneral.html) )

CRAN only builds for selected platforms due to capacity issues, not because it disregards any platform *or* architecture. R packages with non-R code should compile on any architecture. 
It is quite astonishing that you even disregard possible solution to the problem.

In my case, I am facing the issue while building binaries for CRAN packages on Linux. And {KSgeneral} is among ~ 10 packages (out of 21k) which fail on arm64 arch, which underlines the exceptional state of the package and arm64 issues overall.
